version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/ahmedsharyo/crypto-sign-challenge
    steps:
      - checkout
      - run: go test -v ./Test...